server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Usuarios Plazoleta"
appVersion: "1.0.0"
